on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.13
    steps:
      - name: Kopiowanie kodu
        uses: actions/checkout@v4
      - name: Instalacja paczek
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testy
        run: python -m pytest -q tests/


# gh act push
# gh act -l pull_request